<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Webpatser\Uuid\Uuid;

class Invoice extends Model
{
    protected $table = 'invoices';

    protected $fillable = [ 'uuid', 'name', 'email', 'cpf', 'invoice', 'cep', 'street', 'number', 'complement', 'neighborhood', 'city', 'state', 'validated', 'users_id' ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Static::creating(function($model){
            $model->uuid = Uuid::generate()->string;
            $model->validated = '0';
        });
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'users_id', 'id');
    }

    /**
     * @param String $uuid
     * @param array $with
     * @return Invoice|Builder|Model|object|null
     */
    public static function findByUuid(String $uuid, Array $with = [])
    {
        return self::with($with)->where('uuid', $uuid)->first();
    }
}
