<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Webpatser\Uuid\Uuid;

class Permission extends Model
{
    protected $table = 'permissions';

    protected $fillable = ['uuid', 'name', 'reference'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Static::creating(function($model){
            $model->uuid = Uuid::generate()->string;
        });
    }

    /**
     * @return BelongsToMany
     */
    public function profiles(): BelongsToMany
    {
        return $this->belongsToMany(Profile::class, 'profiles_permissions', 'permissions_id', 'profiles_id');
    }

    /**
     * @param String $uuid
     * @param array $with
     * @return Permission|Builder|Model|object|null
     */
    public static function findByUuid(String $uuid, Array $with = [])
    {
        return self::with($with)->where('uuid', $uuid)->first();
    }
}
