<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Webpatser\Uuid\Uuid;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';

    protected $fillable = [ 'uuid', 'name', 'email', 'password', 'cpf', 'profiles_id' ];

    protected $hidden = [ 'password', 'remember_token' ];

    protected $casts = [ 'email_verified_at' => 'datetime' ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Static::creating(function($model){
            $model->uuid = Uuid::generate()->string;
        });
    }

    /**
     * @return BelongsTo
     */
    public function profile(): BelongsTo
    {
        return $this->belongsTo(Profile::class, 'profiles_id', 'id');
    }

    /**
     * @return HasMany
     */
    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class, 'users_id', 'id');
    }

    /**
     * @param String $uuid
     * @param array $with
     * @return User|Builder|Model|object|null
     */
    public static function findByUuid(String $uuid, Array $with = [])
    {
        return self::with($with)->where('uuid', $uuid)->first();
    }
}
